### ISSUE TITLE
Config keywords `Tag` and `Match tagged` are not supported

### ISSUE THREAD

**Issue by ThymoNL** [canonical/libssh#10]
While using Wireshark I ran into an issue of my config not being parsable. I traced this down to `ssh_options_parse_config` returning an error. Upon further investigation it looks like the Tag keyword is not present in the `ssh_config_keyword_table`. There also appears to be no other logic to handle the Tag keyword in an ssh config.

The following config example can be used to reproduce:
```
Math host 192.0.2.2
    Tag test

Match tagged test
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
```

**Comment by ricab** [comment]
Hi @ThymoNL, I suppose you meant to go upstream: https://www.libssh.org/development/

This is just a fork of libssh here.
