### ISSUE TITLE
how to connect multiple clients to one server? 

### ISSUE THREAD

**Issue by Edwardmark** [canonical/libssh#9]
how to connect multiple clients to one server? Could you provide a code examples? Thanks.

**Comment by townsend2010** [comment]
Hi @Edwardmark!

You have entered this in a fork of libssh.  If you need libssh support, please post this upstream at https://gitlab.com/libssh/libssh-mirror/-/issues/?sort=created_date&state=opened&first_page_size=50 or the [libssh mailing list](https://www.libssh.org/communication/).  Thanks!
